-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
     FROM ONLINE_SALE
     WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
     UNION
     SELECT SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
     FROM OFFLINE_SALE
     WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3) total
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC
