-- 코드를 입력하세요
/* 2021년에 가입한 회원 중 상품을 구매한 회원수 */

# SELECT sale.ONLINE_SALE_ID, sale.USER_ID, sale.PRODUCT_ID, sale.SALES_AMOUNT, COUNT(DISTINCT(sale.USER_ID))
# FROM ONLINE_SALE sale
# GROUP BY USER_ID

SELECT YEAR(sale.SALES_DATE) YEAR,
    MONTH(sale.SALES_DATE) MONTH,
    COUNT(DISTINCT info.USER_ID) PUCHASED_USERS,
    ROUND(COUNT(DISTINCT info.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021) ,1) AS PUCHASED_RATIO
FROM USER_INFO AS info
INNER JOIN ONLINE_SALE AS sale
ON sale.USER_ID = info.USER_ID
WHERE YEAR(info.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH