-- 코드를 입력하세요
/* 2021년에 가입한 회원 중 상품을 구매한 회원수 */

# SELECT sale.ONLINE_SALE_ID, sale.USER_ID, sale.PRODUCT_ID, sale.SALES_AMOUNT, COUNT(DISTINCT(sale.USER_ID))
# FROM ONLINE_SALE sale
# GROUP BY USER_ID

SELECT YEAR(o.SALES_DATE) YEAR, MONTH(o.SALES_DATE) MONTH,
    COUNT(DISTINCT o.USER_ID) PUCHASED_USERS,
    ROUND((COUNT(DISTINCT u.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021)),1) PUCHASED_RATIO
FROM USER_INFO u
INNER JOIN ONLINE_SALE o
ON u.USER_ID = o.USER_ID
WHERE YEAR(u.JOINED) = 2021
GROUP BY MONTH
