-- 코드를 입력하세요
SELECT info.FLAVOR
FROM ICECREAM_INFO info
INNER JOIN FIRST_HALF h
ON info.FLAVOR = h.FLAVOR
WHERE (h.TOTAL_ORDER > 3000) AND info.INGREDIENT_TYPE = 'fruit_based'
ORDER BY h.TOTAL_ORDER DESC