-- 코드를 입력하세요
/*  */
SELECT f.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) total
     FROM JULY
     GROUP BY FLAVOR) j
INNER JOIN FIRST_HALF f
ON f.FLAVOR = j.FLAVOR
ORDER BY (j.total+f.TOTAL_ORDER) DESC
LIMIT 3

/* 7월 아이스크림 총 주문량 */
# SELECT FLAVOR, SUM(TOTAL_ORDER)
# FROM JULY
# GROUP BY FLAVOR
