-- 코드를 입력하세요
SELECT q.MEMBER_NAME, rev.REVIEW_TEXT, DATE_FORMAT(rev.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM (SELECT mem.MEMBER_NAME, mem.MEMBER_ID
     FROM MEMBER_PROFILE mem
     INNER JOIN REST_REVIEW rev
     ON mem.MEMBER_ID = rev.MEMBER_ID
     GROUP BY mem.MEMBER_ID
     ORDER BY count(REVIEW_ID) DESC
     LIMIT 1) q
INNER JOIN REST_REVIEW rev
ON q.MEMBER_ID = rev.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
