-- 코드를 입력하세요
SELECT pro.PRODUCT_CODE, SUM(pro.PRICE * off.SALES_AMOUNT) as SALES
FROM PRODUCT as pro
INNER JOIN OFFLINE_SALE as off
ON pro.PRODUCT_ID = off.PRODUCT_ID
GROUP BY pro.PRODUCT_CODE
ORDER BY SALES DESC, pro.PRODUCT_CODE ASC