-- 코드를 입력하세요
/* 상품ID, 상품명, 총매출(5월간 판매된 총량*가격)*/
SELECT pr.PRODUCT_ID, pr.PRODUCT_NAME
, pr.PRICE*sq.total TOTAL_SALES
FROM (SELECT od.PRODUCT_ID, SUM(od.AMOUNT) total
   FROM FOOD_ORDER od 
   WHERE DATE_FORMAT(od.PRODUCE_DATE, '%Y-%m') = '2022-05' 
   GROUP BY od.PRODUCT_ID) sq
INNER JOIN FOOD_PRODUCT pr
ON pr.PRODUCT_ID = sq.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, sq.PRODUCT_ID ASC

/* 5월간 판매된 상품별 총량 */
# SELECT od.PRODUCT_ID, SUM(od.AMOUNT)
#    FROM FOOD_ORDER od 
#    WHERE DATE_FORMAT(od.PRODUCE_DATE, '%Y-%m') = '2022-05' 
#    GROUP BY od.PRODUCT_ID